# Generated by Django 4.1.5 on 2023-01-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_product_cart_to_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart_to_product',
        ),
        migrations.AddField(
            model_name='product',
            name='cart_to_product',
            field=models.ManyToManyField(blank=True, to='shop.cartitem'),
        ),
    ]
