# Generated by Django 4.1.5 on 2023-01-08 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_cartitem_cart_to_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='same_product',
            field=models.IntegerField(default=1),
        ),
    ]
