# Generated by Django 4.1.5 on 2023-01-09 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_multipleproduct_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multipleproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
        ),
    ]
